<?xml version="1.0" encoding="utf-8"?> 
<definitions 
	xmlns:http="http://schemas.xmlsoap.org/wsdl/http/" 
	xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" 
	xmlns:s="http://www.w3.org/2001/XMLSchema" 
	xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/" 
	xmlns:tm="http://microsoft.com/wsdl/mime/textMatching/" 
	xmlns:mime="http://schemas.xmlsoap.org/wsdl/mime/" 
	xmlns="http://schemas.xmlsoap.org/wsdl/"
	xmlns:p="http://service.ebms.edi.cecid.hku.hk/" 
	targetNamespace="http://service.ebms.edi.cecid.hku.hk/"
>
<types>
</types>
<message name="EbmsRequestMsg">
  <part name="cpaId" type="s:string" /> 
  <part name="service" type="s:string" /> 
  <part name="action" type="s:string" /> 
  <part name="convId" type="s:string" />
  <part name="fromPartyId" type="s:string" />
  <part name="fromPartyType" type="s:string" />
  <part name="toPartyId" type="s:string" />
  <part name="toPartyType" type="s:string" />
  <part name="refToMessageId" type="s:string" />
  <part name="serviceType" type="s:string" />
</message>
<message name="EbmsResponseMsg">
  <part name="message_id" type="s:string" /> 
</message>
<portType name="EbmsSend">
  <operation name="Request">
    <input message="p:EbmsRequestMsg" /> 
    <output message="p:EbmsResponseMsg" /> 
  </operation>
</portType>
<binding name="EbmsSoapHttpSend" type="p:EbmsSend">
  <soap:binding transport="http://schemas.xmlsoap.org/soap/http" style="document" /> 
  <operation name="Request">
    <soap:operation soapAction="ebmssend" style="document" /> 
    <input>
      <soap:body use="literal" /> 
    </input>
    <output>
      <soap:body use="literal" /> 
    </output>
  </operation>
</binding>
<service name="EbmsOutbound">
  <documentation>Documentation not available.</documentation> 
  <port name="EbmsSend" binding="p:EbmsSoapHttpSend">
    <soap:address location="http://127.0.0.1:8080/corvus/httpd/ebms/sender" /> 
  </port>
</service>
</definitions>